FROM golang:1.22.0 as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY ./ ./

RUN go test ./...

RUN GOOS=linux GOARCH=arm GOARM=5 CGO_ENABLED=0 go build

FROM alpine:3.16.2

COPY --from=builder /app/openevse-statsd /bin/openevse-statsd
WORKDIR /var/lib/openevse-statsd/

CMD ["/bin/openevse-statsd","-configFile=/var/lib/openevse-statsd/config.json"]
